"""
Internationalization (i18n) module for SC_Toolbox.

Uses Python's built-in ``gettext`` for PO/MO-based translations.
Translators use Poedit (free visual editor) to edit ``.po`` files —
no coding knowledge required.

Architecture:
    - Single unified catalog (``sc_toolbox`` domain) for ALL strings
      across the launcher and every tool
    - All translations live in ``locales/<lang>/LC_MESSAGES/sc_toolbox.mo``
    - Missing translations fall back to the English source string
    - Language preference read from ``SC_TOOLBOX_LANG`` env var (set by launcher)

Translation files:
    - ``locales/SC_Toolbox_Source.pot`` — auto-generated source template
      (regenerated by ``tools/extract_strings.py``, safe to overwrite)
    - ``locales/<lang>/LC_MESSAGES/sc_toolbox.po`` — translator's work
      (NEVER touched by any script)
    - ``locales/<lang>/LC_MESSAGES/sc_toolbox.mo`` — compiled binary
      (generated from .po via ``msgfmt``)
"""
from __future__ import annotations

import gettext
import logging
import os
from pathlib import Path

log = logging.getLogger(__name__)

_DOMAIN = "sc_toolbox"

# Active translation
_trans: gettext.GNUTranslations | gettext.NullTranslations = gettext.NullTranslations()
_current_lang: str = "en"


def init(lang: str = "en", locale_dir: str | None = None) -> None:
    """Initialise the translation catalog.

    Parameters
    ----------
    lang:
        ISO 639-1 language code (e.g. ``"en"``, ``"de"``, ``"fr"``).
    locale_dir:
        Path to the ``locales/`` directory.
        If *None*, defaults to ``<project_root>/locales/``.
    """
    global _trans, _current_lang
    _current_lang = lang

    if locale_dir is None:
        project_root = str(Path(__file__).resolve().parent.parent)
        locale_dir = os.path.join(project_root, "locales")

    _trans = gettext.translation(
        _DOMAIN, locale_dir, languages=[lang], fallback=True,
    )
    log.info("i18n: catalog loaded (lang=%s, dir=%s)", lang, locale_dir)


def register_skill(domain: str, locale_dir: str) -> None:
    """No-op kept for backward compatibility with app_bootstrap.

    All strings now use a single unified catalog loaded by ``init()``.
    """
    pass


def get_language() -> str:
    """Return the active language code."""
    return _current_lang


def _(msg: str) -> str:
    """Translate *msg* using the unified catalog."""
    return _trans.gettext(msg)


# s_() is an alias — all strings are in one catalog now.
s_ = _


def N_(msg: str) -> str:
    """Mark *msg* for extraction without translating it.

    Use this for strings defined at module level (e.g. in data structures)
    that will be translated later at display time via ``_()``.
    """
    return msg


def available_languages(base_dir: str) -> list[str]:
    """Scan the ``locales/`` directory and return available language codes.

    Returns a sorted, deduplicated list that always starts with ``"en"``.
    """
    langs: set[str] = {"en"}

    root_locales = os.path.join(base_dir, "locales")
    _collect_langs(root_locales, langs)

    result = sorted(langs)
    if "en" in result:
        result.remove("en")
        result.insert(0, "en")
    return result


def _collect_langs(locale_dir: str, out: set[str]) -> None:
    """Add language codes found in a ``locales/`` directory to *out*."""
    if not os.path.isdir(locale_dir):
        return
    try:
        for entry in os.listdir(locale_dir):
            lc_path = os.path.join(locale_dir, entry, "LC_MESSAGES")
            if os.path.isdir(lc_path):
                out.add(entry)
    except OSError:
        pass
